# Font configuration
[font]
normal = { family = "CaskaydiaCove Nerd Font" }
offset = { x = 0, y = 3 }
size = 11.25

[window]
dimensions = { columns = 150, lines = 30 }
dynamic_title = false
opacity = 0.95
decorations = "full"
dynamic_padding = false
